# Generated by Django 4.2.17 on 2025-01-02 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flex_catalog', '0003_alter_flexiblecatalogmodel_name'),
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        ('custom_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExCatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('item_type', models.CharField(choices=[('COURSE', 'Course'), ('LSEQ', 'Learning Sequence')], default='COURSE', max_length=8)),
                ('course_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_overviews.courseoverview')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='LearningSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('courses', models.ManyToManyField(blank=True, related_name='linked_learning_sequences', to='course_overviews.courseoverview')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalOrgCatalog',
            fields=[
                ('flexiblecatalogmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flex_catalog.flexiblecatalogmodel')),
                ('items', models.ManyToManyField(blank=True, related_name='linked_catalogs', to='custom_catalog.excatalogitem')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_catalog.externalorg')),
            ],
            options={
                'abstract': False,
            },
            bases=('flex_catalog.flexiblecatalogmodel',),
        ),
        migrations.AddField(
            model_name='excatalogitem',
            name='learning_sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_catalog.learningsequence'),
        ),
    ]
